# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2070acbbd239101f2489b1289c45c251cdebe4daa941975f6b7ba4237bebb08561f154f1f3e1a466a358c31467655725a4b54ac60d52e2926aa4da7a57fc3078

test:
  secret_key_base: 9284a78fd9d26d4eaaddd3685ea0ae308faff5b94a2ff7aa64cff6040c1078a803ac78b9829cefb79320c928338e287b414e439807cd0b6e7cb0fc9befa277d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
